apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-deploy
  name: my-deploy
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30007
  selector:
    app: my-deploy
  type: NodePort
status:
  loadBalancer: {}
